"""Skill Library 数据模型（论文 §2.2 + Appendix A + E.5 模板 + open_details/skill_grasp.md 格式标杆）。

skill = **结构化知识文档**（不是可执行函数），以 in-context guidance 注入 actor prompt。
磁盘格式 = 单个 markdown 文件（YAML frontmatter + 固定小节），文件系统即索引：

```
skill_library/
├── index.json                  # 索引（name → category/status/path/一句话描述），admit 时原子更新
├── grasping/piper_topdown_grasp.md
├── localization/sam3_prompting.md
└── ...
```

四要素（Appendix A 逐字）：(i) Problem（触发失败 trace 提炼的失败特征）；
(ii) When to Apply（情景检索 guard）；(iii) Strategy（验证过的修复策略 + code sketch）；
(iv) Origin task(s)。格式标杆追加：Evidence 必须 seed 级实证（skill_grasp.md 纪律）。
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

import yaml

# 入库条目状态机：candidate（actor 上报待审）→ admitted（coordinator 审计通过）
#                → retired（被新条目取代/证伪）
VALID_STATUS = ("candidate", "admitted", "retired")

# 磁盘小节的固定顺序（渲染/解析共用）
SECTION_ORDER = ["Problem", "When to Apply", "Strategy", "Evidence", "Limitations"]


@dataclass
class SkillEntry:
    """一条 skill（知识文档）。code_sketch 允许为空（纯策略条目）。"""

    name: str                       # 唯一键，kebab-case，= 文件名（不含 .md）
    category: str                   # 自由文本类目（论文：不预设 taxonomy）
    problem: str                    # (i) 失败特征
    when_to_apply: str              # (ii) 检索 guard（条目要点用 "- " 列表行）
    strategy: str                   # (iii) 修复策略正文
    origin_tasks: list[str] = field(default_factory=list)  # (iv) 来源任务
    code_sketch: str = ""           # 可选：验证过的代码草图（只允许契约 API）
    evidence: str = ""              # seed 级实证（格式标杆纪律：必须引用具体 seed 成败）
    limitations: str = ""           # 可选
    status: str = "candidate"
    validation_debug: str = ""      # 如 "3/3"（debug seeds 成功率）
    validation_heldout: str = ""    # 如 "5/10"（held-out 一次性验证）
    created: str = ""
    updated: str = ""
    description: str = ""           # 一句话覆盖范围（frontmatter + index.json 用）

    # ------------------------------------------------------------------
    # 渲染：SkillEntry → SKILL.md 文本
    # ------------------------------------------------------------------
    def to_markdown(self) -> str:
        fm = {
            "name": self.name,
            "description": self.description or self.problem.split("\n")[0][:120],
            "category": self.category,
            "status": self.status,
            "origin_tasks": self.origin_tasks,
            "created": self.created,
            "updated": self.updated,
            "validation": {"debug": self.validation_debug, "heldout": self.validation_heldout},
        }
        parts = ["---\n" + yaml.safe_dump(fm, allow_unicode=True, sort_keys=False).strip() + "\n---\n"]
        parts.append(f"\n# {self.name}\n")
        parts.append("\n> **Purpose:** " + (self.description or self.problem.split("\n")[0][:120]) + "\n")
        parts.append("> **Ownership:** Coordinator adds generalizable patterns. "
                     "Actors do not edit this file.\n")
        body = {
            "Problem": self.problem,
            "When to Apply": self.when_to_apply,
            "Strategy": self.strategy,
            "Evidence": self.evidence,
            "Limitations": self.limitations,
        }
        if self.code_sketch.strip():
            # Code Sketch 作为 Strategy 的 ### 子小节（解析器从 Strategy 内抽取）
            body["Strategy"] = (self.strategy.strip()
                                + "\n\n### Code Sketch\n\n```python\n"
                                + self.code_sketch.strip() + "\n```")
        for sec in SECTION_ORDER:
            text = body[sec].strip()
            if not text:
                continue
            parts.append(f"\n## {sec}\n\n{text}\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # 解析：SKILL.md 文本 → SkillEntry
    # ------------------------------------------------------------------
    @classmethod
    def from_markdown(cls, text: str) -> "SkillEntry":
        fm: dict = {}
        body = text
        m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.DOTALL)
        if m:
            fm = yaml.safe_load(m.group(1)) or {}
            body = m.group(2)

        # 按 "## " 小节切分；### Code Sketch 从 Strategy 段里单独抽出
        sections: dict[str, str] = {}
        current = None
        buf: list[str] = []
        for line in body.splitlines():
            h = re.match(r"^##\s+(.+?)\s*$", line)
            if h:
                if current:
                    sections[current] = "\n".join(buf).strip()
                current = h.group(1)
                buf = []
            elif current:
                buf.append(line)
        if current:
            sections[current] = "\n".join(buf).strip()

        strategy = sections.get("Strategy", "")
        code_sketch = ""
        sketch_m = re.search(r"###\s*Code Sketch\s*\n+```(?:python|py)?\s*\n(.*?)```",
                             strategy, re.DOTALL)
        if sketch_m:
            code_sketch = sketch_m.group(1).strip()
            strategy = (strategy[: sketch_m.start()] + strategy[sketch_m.end():]).strip()
        if not code_sketch:  # 兼容：Strategy 外独立小节的写法
            for sec_name, sec_text in list(sections.items()):
                sketch_m = re.search(r"```(?:python|py)?\s*\n(.*?)```", sec_text, re.DOTALL)
                if sec_name.lower().startswith("code") and sketch_m:
                    code_sketch = sketch_m.group(1).strip()

        validation = fm.get("validation") or {}
        return cls(
            name=fm.get("name", ""),
            category=fm.get("category", "uncategorized"),
            description=fm.get("description", ""),
            status=fm.get("status", "candidate"),
            origin_tasks=list(fm.get("origin_tasks") or []),
            created=str(fm.get("created", "") or ""),
            updated=str(fm.get("updated", "") or ""),
            validation_debug=str(validation.get("debug", "") or ""),
            validation_heldout=str(validation.get("heldout", "") or ""),
            problem=sections.get("Problem", ""),
            when_to_apply=sections.get("When to Apply", ""),
            strategy=strategy,
            evidence=sections.get("Evidence", ""),
            limitations=sections.get("Limitations", ""),
            code_sketch=code_sketch,
        )


# ---------------------------------------------------------------------------
# findings.md（E.3 actor 上报 schema，逐字模板见 prompts.py::FINDINGS_TEMPLATE）
# coordinator 审计的输入；此处只做轻量结构化解析（小节切分），不做强校验。
# ---------------------------------------------------------------------------

FINDINGS_SECTIONS = ["Root Cause(s)", "What Fixed It", "Perception Prompts That Worked",
                     "Generalizable Patterns", "Task-Specific Quirks", "Stage 2 Success Rate"]


def parse_findings(text: str) -> dict[str, str]:
    """findings.md → {小节名: 文本}。缺失小节 = 空字符串（actor 自由发挥时不炸）。"""
    out: dict[str, str] = {s: "" for s in FINDINGS_SECTIONS}
    out["Task"] = ""
    current = None
    buf: list[str] = []
    for line in text.splitlines():
        h = re.match(r"^#{2,3}\s*(.+?)\s*$", line)
        if h:
            if current:
                out[current] = "\n".join(buf).strip()
            current = h.group(1).strip().rstrip(":")
            # 统一别名（actor 可能写 Task: X / 带 suite 前缀）
            for canon in ["Task"] + FINDINGS_SECTIONS:
                if current.lower().startswith(canon.lower()):
                    current = canon
                    break
            buf = []
        elif current:
            buf.append(line)
    if current:
        out[current] = "\n".join(buf).strip()
    return out
