/**
 * ASPIRE hero — a wall of simulation rollouts behind a full-screen stream of
 * the agent's control code, which cycles through the ACTUAL multi-turn fixes
 * ASPIRE made on the cube_stack task (see docs/logs/2026-05-01-cube-stack.md):
 * GraspNet → size-filtered geometric masks, SAM3 colour verification, grasp
 * z-height top-edge → mid-height (0/25 → 25/25), and median → OBB-centre XY.
 *
 * Edits are fixed and logically sound (old code struck red → fixed code typed
 * green); nothing runs an LLM live. "ASPIRE" sits over a centre vignette.
 */
(function () {
  "use strict";

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const rand = (a, b) => a + Math.floor(Math.random() * (b - a + 1));
  function debounce(fn, ms) { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; }
  const tokenize = (line) => window.AspireSyntax.tokenizePythonLine(line, { prefix: "hl" });

  let running = true;

  document.addEventListener("DOMContentLoaded", () => { initWallVisibility(); initCodeLayer(); });

  /* ── The skill wall is one pre-rendered loop (assets/videos/skill_grid_loop.mp4)
     — a single decode instead of dozens of <video>s. Pause it (and the code
     scroll) whenever the grid hero is off-screen. ── */
  function initWallVisibility() {
    const section = document.getElementById("grid-hero");
    const v = document.getElementById("wall-video");
    if (!section || !("IntersectionObserver" in window)) return;
    new IntersectionObserver((entries) => {
      running = entries[0].isIntersecting;
      if (v) { if (running) { const p = v.play(); if (p) p.catch(() => {}); } else v.pause(); }
    }, { threshold: 0.02 }).observe(section);
  }

  /* ── The fixed program (final state) + the real fixes that produced it ── */
  const PROGRAM = [
    "# aspire/skills/cube_stack.py  —  generated by ASPIRE",
    "import numpy as np",
    "",
    "def localize_cube(rgb, depth, K, T, prompt):",
    "    masks = segment_sam3(rgb, prompt, min_px=50, max_px=12000)   # size-filtered",
    "    mask  = pick_by_color(masks, prompt)            # SAM3 confuses red / green",
    "    pts   = mask_to_world_points(mask, depth, K, T)",
    "    pts   = pts[np.isfinite(pts).all(axis=1)]",
    "    center = obb_center(pts)                        # robust to camera-facing bias",
    "    top_z  = np.percentile(pts[:, 2], 95)",
    "    bot_z  = np.percentile(pts[:, 2], 5)",
    "    return center, top_z, bot_z",
    "",
    'red_c,   red_top, red_bot = localize_cube(rgb, depth, K, T, "red cube")',
    'green_c, green_top, _     = localize_cube(rgb, depth, K, T, "green cube")',
    "",
    "# grasp at mid-height for a solid two-finger contact",
    "grasp_z = (red_top + red_bot) / 2.0",
    "grasp   = [red_c[0], red_c[1], grasp_z]",
    "",
    "open_gripper()",
    "move_pose(grasp + [0, 0, 0.10], quat_down)          # pre-grasp",
    "move_pose(grasp, quat_down)",
    "close_gripper()",
    "if gripper_width() < 0.015:                         # verify grasp before lift",
    "    return regrasp()",
    "lift(grasp, green_top + 0.12)",
    "place_z = green_top + cube_h * 0.5",
    "move_pose([green_c[0], green_c[1], place_z], quat_down)",
    "open_gripper()",
    "",
  ];

  // Each edit: the buggy lines an earlier turn had (shown red), replaced by the
  // current PROGRAM lines (shown green). Real changes from the fix-loop log.
  // Ordered so consecutive entries form 3 spread-out PAIRS that we cycle.
  const EDITS = [
    // ── pair 0 ──
    { line: 4, buggy: [                                       // GraspNet → size-filtered SAM3 + colour
        "    mask  = graspnet_best_grasp(rgb, prompt)       # GraspNet → edge grasps",
        "    # (single mask, selected by score)" ] },
    { line: 16, buggy: [                                      // grasp z: 0/25 → 25/25
        "# grasp at the very top edge of the cube",
        "grasp_z = red_top + 0.002                          # 0/25 — too high" ] },
    // ── pair 1 ──
    { line: 7, buggy: [                                       // median → OBB centre
        "    pts   = pts",
        "    center = np.median(pts, axis=0)                 # biased toward camera face" ] },
    { line: 24, buggy: [                                      // add grasp verification before lift
        "if gripper_width() < 0.0:                           # no contact check",
        "    pass" ] },
    // ── pair 2 ──
    { line: 9, buggy: [                                       // max/min → robust percentile
        "    top_z  = float(pts[:, 2].max())                 # outlier-sensitive",
        "    bot_z  = float(pts[:, 2].min())" ] },
    { line: 26, buggy: [                                      // lift higher + centre the place
        "lift(grasp, green_top + 0.02)                       # too low — top cube clips",
        "place_z = green_top + cube_h" ] },
  ];
  // Each edit's "fixed" form is just the current PROGRAM lines at that range.
  EDITS.forEach((e) => { e.fixed = PROGRAM.slice(e.line, e.line + e.buggy.length); });
  const PAIRS = [[EDITS[0], EDITS[1]], [EDITS[2], EDITS[3]], [EDITS[4], EDITS[5]]];

  function initCodeLayer() {
    const host = document.getElementById("hero-code");
    if (!host) return;
    const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    const N = PROGRAM.length;
    const lineHtml = (t) => `<div class="hc-line">${t === "" ? "&nbsp;" : tokenize(t)}</div>`;
    const body = PROGRAM.map(lineHtml).join("");
    host.innerHTML = `<div class="hc-scroll">${body}${body}</div>`;
    const scroll = host.querySelector(".hc-scroll");
    const nodes = scroll.querySelectorAll(".hc-line");
    if (prefersReduced) return;

    let copyH = 0, lineH = 20;
    const measure = () => { lineH = nodes[0] ? nodes[0].getBoundingClientRect().height : 20; copyH = lineH * N; };
    measure();
    window.addEventListener("resize", debounce(measure, 250));

    // continuous slow scroll
    let offset = 0, last = null;
    function tick(ts) {
      if (last == null) last = ts;
      const dt = Math.min(0.05, (ts - last) / 1000); last = ts;
      if (running && copyH > 0) { offset += 14 * dt; if (offset >= copyH) offset -= copyH; scroll.style.transform = `translateY(${-offset}px)`; }
      requestAnimationFrame(tick);
    }
    requestAnimationFrame(tick);

    // render a line (both copies) with optional state class
    const setLine = (idx, text, cls) =>
      [nodes[idx], nodes[idx + N]].forEach((nd) => {
        if (!nd) return;
        nd.innerHTML = text === "" ? "&nbsp;" : tokenize(text);
        nd.classList.remove("hc-add", "hc-del");
        if (cls) nd.classList.add(cls);
      });

    const isVisible = (line, len) => {
      const first = Math.floor(offset / lineH);
      const vis = Math.max(6, Math.floor(window.innerHeight / lineH));
      const rel = (line - first + N) % N;            // position of the block top in the loop
      return rel >= 1 && rel + len <= vis - 1;
    };

    // play one edit: show the old (buggy) lines red, then the fixed lines green
    async function playEdit(e) {
      for (let k = 0; k < e.buggy.length; k++) setLine(e.line + k, e.buggy[k], "hc-del");
      await sleep(700);
      for (let k = 0; k < e.fixed.length; k++) setLine(e.line + k, e.fixed[k], "hc-add");
      await sleep(1100);
      for (let k = 0; k < e.fixed.length; k++) setLine(e.line + k, e.fixed[k], null);
    }

    async function editLoop() {
      await sleep(1200);
      let p = 0;
      // eslint-disable-next-line no-constant-condition
      while (true) {
        if (running && copyH > 0) {
          // Cycle the 3 pairs in order; play each pair's 2 edits together.
          await Promise.all(PAIRS[p].map((e) => playEdit(e)));
          p = (p + 1) % PAIRS.length;
          await sleep(rand(600, 1000));   // short gap between pairs
        } else await sleep(300);
      }
    }
    editLoop();
  }
})();
